디자인 수정
mash-up-kr/AllNight-Android pull request #57
Opened 2019-08-29 19:48 UTC by ArimYeon

디자인 수정
영문 수정

2019-09-01 04:23 UTC, jujinkim requested changes

2019-09-01 04:23 UTC, jujinkim commented on app/src/main/java/com/mashup/allnight/RecipeListActivity.kt
> +        var i = 0
이거혹시 0인지 1인지에 따라 뷰모드 분기칠 때 쓰는 변수인가요?

그럼 var i = 0, i = 1 - i보다는
var isSingleViewMode = true, 
누를 때 isSingleViewMode = !isSingleViewMode
이런식으로 변수 이름과 타입을 거 구체적으로 해주는게 좋습니다
a, b, c 등의 의미를 전혀 알 수 없는 변수/함수 네이밍은 가장 지양해야 될 요소중 하나입니다.

추가로, 이런 변수는 이 액티비티 전역에서 사용되므로 onCreate 내부보다는 Class안에 전역변수로 넣어주는건 어떨지 제안해봅니다.

2019-09-01 04:23 UTC, jujinkim commented on app/src/main/java/com/mashup/allnight/BucketActivity.kt
> +            val items: ArrayList<String> = arrayListOf()
큰 문제는 없지만, 위 next_button_bucket과 완전히 동일한 기능을 하는 버튼이므로, 구현 내용을 아예 따로 메소드로 빼고(예를들면 moveToRecipeList 같은 이름으로), 위 next_button_bucket과 이 bucket_search_button 에서 따로 뺀 메소드를 호출해주면 나중에 코드 읽기나 수정이 훨씬 편할 수 있습니다.

2019-09-03 03:52 UTC, ArimYeon commented on app/src/main/java/com/mashup/allnight/BucketActivity.kt
> +            val items: ArrayList<String> = arrayListOf()
수정완료했습니다

2019-09-03 03:52 UTC, ArimYeon commented on app/src/main/java/com/mashup/allnight/RecipeListActivity.kt
> +        var i = 0
수정완료했습니다

2019-09-03 03:52 UTC, merged